### ISSUE TITLE
yaml config `on_before_training` actions not working

### ISSUE THREAD

**Issue by cosmicBboy** [gridai/gridai#131]
## 🐛 Bug

hi! I rely on the `on_before_training` action to load up artifacts from a previous training run so that I can continue training.

### Expected behavior

This feature was working for me over the past few weeks and only stopped working this week.

My training script expects artifacts to be present in the `/artifacts` directory

### Current behavior

Training script raises a file not found error.

### To Reproduce

Steps to reproduce the issue

My config file looks like:

```
compute:
  train:
    actions:
      on_before_training_start:
        - echo "ON BEFORE TRAINING"
        - grid login --username ${GRID_USERNAME} --key ${GRID_API_KEY}
        - grid artifacts ${GRID_ARTIFACTS_RUNS_OR_EXPERIMENTS} --download_dir /artifacts || echo 'skip artifacts download'
```

Files should be in `/artifacts`.

When I look into the build/experiment logs I can't find the `echo` statement (before this would work too).

### Environment

 - OS (e.g., Windows): MacOS
 - Browser (e.g., Chrome, Safari): Chrome
 - CLI version: v0.3.92

### Additional context

NA
