### ISSUE TITLE
PackageCompiler option for julia

### ISSUE THREAD

**Issue by jlperla** [gridai/gridai#65]
After Julia support is tested (e.g. in #63 ) I think a great next step would be to try to add in support for package compilation.  What this would do is compile a whole bunch of stuff into an image.  The difference in latency is enormous.

The vscode extension has a feature to do this https://www.julia-vscode.org/docs/stable/userguide/compilesysimage/   which would automatically load up system images if they exist.  The difference here is that any vscode session on the container and/or run doesn't need to worry about swapping between compiled sysimages, so I think it is safe to overwrite things.  But you can look at vscodes approach https://github.com/julia-vscode/julia-vscode/blob/1da85dc37b54723c1bc4b313d2c11a974c7656b4/scripts/tasks/task_compileenv.jl

So my suggestion here is the following.  The user has an option when creating a julia image by
- set the flag `--build-sysimage`  to true.  This has to be off by default because it doesn't always work.  It is also necessary to be able to see the full build log to see why it may not have worked and for the error to be caught.
- optionally set `--sysimage-precompile-script` or something like that. You might want to set it to your main grid training script, or to call that after modifying some parametesr, etc
  - For exmaple, with a bayesian thing I might set it to be `julia --project --threads auto fit.jl --num_samples 100` or something like that, so it would figure out all of the functions it needs by that point and it doesn't need to go to full completion.  

OK, then with these, if the user sets`--build-sysimage` to be true, then:
- You would want to install the packagecompiler in the image building script in the global environment (i.e. do not activate the project!)  with something like
```bash
julia --threads auto -e 'using Pkg; Pkg.add([\"IJulia\", \"PackageCompiler\"])
```
That would do the IJulia and PackageCompiler, both of which should be in the global environment.  Don't install package compiler unless the user asks for this feature.

- Then call a julia script like `julia --threads auto build_sysimage.jl $sysimage-precompile-script` where you can get that script from the optional arugment above.  The file would look something like:

```julia
import Pkg, Libdl, PackageCompiler

precompile_script = ARGS[1]

precompile_execution_file= isfile(precompile_script) ? precompile_script : nothing

project = Pkg.API.read_project("Project.toml")  # could verify it is there and error handle otherwise.
used_packages = Symbol.(collect(keys(project.deps)))

@info "Now building a custom sysimage using precompile file $precompile_script"
PackageCompiler.create_sysimage(used_packages; project = "Project.toml", precompile_execution_file, replace_default=true)
```
The `replace_default` overwrites the julia system image, so you would need to make sure it ends up in the container.  Normally this is a questionable idea, but for this case it is fine since one-project-per-image makes sense  (either in an interactive or in a run based model).  After you do this, though, it means that vscode, jupyer, and the scripts would all have stuff compiled right into the package.  So you can call it as you would normally,
```bash
julia --project --threads auto myscript.jl --arg1 1
```
etc.  and it should be all set.

**Comment by jlperla** [comment]
@rlizzo   see here.  This would be the feature that drives latency to near zero for running an experiment.  Otherwise the fixed cost of startup up julia and compiling it at the beginning of each experiment (or interactive session) could dominate.

**Comment by jlperla** [comment]
A few things:
- I made a better script for package compilation if this was ever going to go into core support.  See https://github.com/HighDimensionalEconLab/HMCExamples.jl/blob/main/deps/create_sysimage.jl  and the referenced code in the Julia vscode extension.  Some of this may end up directly in packagecompiler.jl before too long as well, which can simplify it.
- For CLI projects in particular, it seems that this makes a huge difference.  The julia argparse package I chose has a lot of precompilation/compilation overhead - which makes it expensive in terms of an upfront cost to start scripts.  This isn't a problem on your own computer, but makes it tricky spinning things up on grid.

An alternative prior to putting direct package compiler support into grid is instead to let people do it themselves.  For example, in the https://github.com/HighDimensionalEconLab/HMCExamples.jl#package-compilation repo maybe the user could go:
```yaml
 actions:
      on_image_build:
            - julia --threads auto -e 'using Pkg; Pkg.add(\"PackageCompiler\")'
            - julia --threads auto ./deps/create_sysimage.jl
```
Or if using MKL:
```yaml
 actions:
      on_image_build:
            - julia --threads auto -e 'using Pkg; Pkg.add(\"MKL\")'
            - julia --threads auto -e 'using Pkg; Pkg.add(\"PackageCompiler\")'
            - julia --threads auto ./deps/create_sysimage.jl
```
And this would generate the quasi-standard named `JuliaSysimage.dll` in the root of the package and container.  Later when you support containers for interactice sessions, this would be loaded automtically by the vscode extension as well.

At that point, the only "gotcha" is that we would need to change the julia commandline flags because we need to tell it to use the custom sysimage before the script name.  i.e. you need to call it like the following
```bash
julia --project --sysimage JuliaSysimage.so --threads auto bin/fit_rbc_1_kalman.jl --num_samples 1000
```
Note that the `--sysimage JuliaSysimage.so` needs to be in the flags before the actual script.  One suggestion is that this is part of a more general feature of letting people give custom `julia` flags in a yaml config file/CLI?  Maybe even an all of nothing toggle of replacing all julia flags with their custom ones?

**Comment by jlperla** [comment]
Actually, there is one other alternative to this if getting the julia flags right is too difficult. 
 I added in a feature in https://github.com/HighDimensionalEconLab/HMCExamples.jl/blob/main/deps/create_sysimage.jl so that it can replace the default sysimage.  Just to be clear, this is a terrible idea in general, especially on a desktop, but maybe it will work in this case since it means no custom flags are required.  If so, maybe something like
```yaml
 actions:
      on_image_build:
            - julia --threads auto -e 'using Pkg; Pkg.add(\"MKL\")'
            - julia --threads auto -e 'using Pkg; Pkg.add(\"PackageCompiler\")'
            - julia --threads auto ./deps/create_sysimage.jl --replace_default
```
Could work?
