### ISSUE TITLE
grid run config parsing error: Invalid config: missing `compute` key

### ISSUE THREAD

**Issue by cosmicBboy** [gridai/gridai#85]
## 🐛 Bug

False positive error even when using a config file similar to what's presented in the docs: https://docs.grid.ai/products/run-run-and-sweep-github-files/yaml-configs/yaml-api#grid-spec-overview

### Expected behavior

With a `compute` key, the error shouldn't be there

### Current behavior

error:
```
Error: Invalid value: Invalid config: missing `compute` key.
```

### To Reproduce

Steps to reproduce the issue

Error should be reproducible with `grid run --config config.yml` where `config.yml` is a valid config file (following the docs)

### Environment

 - OS (e.g., Windows): MacOS
 - Browser (e.g., Chrome, Safari): NA
 - CLI version: Grid CLI (v0.3.75)

### Additional context

The bug is in the grid cli file `cli/grid_run.py` line 504:
```
if not _grid_config.get('compute') or _grid_config['compute']['train']:
    raise click.BadParameter("Invalid config: missing `compute` key.")
```

is missing the parens:

```
if not (_grid_config.get('compute') or _grid_config['compute']['train']):
```

**Comment by luiscape** [comment]
@cosmicBboy thank you. Would you share here the `config.yml` that you used (redact any personal information).

**Comment by cosmicBboy** [comment]
```
compute:
  provider:
    credentials: ${GRID_PROVIDER_CREDENTIALS}
    region: us-east-1
    vendor: aws

  train:
    disk_size: 200
    instance: t2.2xlarge
    cpus: 7
    gpus: 0
    memory: 32G
    framework: torch
    datastore_name: ${GRID_DATASTORE_NAME}
    datastore_version: ${GRID_DATASTORE_VERSION}
    datastore_mount_dir: ${GRID_DATASTORE_MOUNT_DIR}

    environment:
      GRID_USERNAME: ${GRID_USERNAME}
      GRID_API_KEY: ${GRID_API_KEY}

    actions:
      on_image_build:
        - apt-get install wget -y
        - pip install lightning-grid
```
