### ISSUE TITLE
Secure secrets or credentials for YAML configs and actions

### ISSUE THREAD

**Issue by ChenghaoMou** [gridai/gridai#88]
## 🚀 Feature

Similar to [encrypted-secrets](https://docs.github.com/en/actions/reference/encrypted-secrets) for Github actions, we need this to hide api-keys to config lighting 3rd-party loggers and any potential credentials user might want to use.

### Description

In lightning config, we can do this to create a logger instance
```yaml
trainer:
  logger:
    class_path: pytorch_lightning.loggers.CometLogger
    init_args:
      api_key: xxxxxxx
      project_name: 'tweet-eval'
      experiment_name: 'distilbert-base-uncased'
```
But currently I can't find a secure way to apply the api_key value without exposing it in my config files.

If we can create an encrypted api through grid, then we can decrypt/apply the api on the fly
```yaml
hyper_params:
  settings:
    strategy: grid_search
  params:
    config: lightning.yaml
    model.learning_rate: uniform(0.0001, 0.002, 2)
    trainer.logger.init_args.api_key: encrypted_secret
```

### Motivation

To avoid the need to explicitly use apis, tokens or credentials in the config files.
