### ISSUE TITLE
Unable to list datastores with name when datastore and version exists

### ISSUE THREAD

**Issue by cosmicBboy** [gridai/gridai#91]
## 🐛 Bug

Using a yaml config file leads to false positive error when specifying datastore_name and datastore_version

When `my_datastore` and version `1` do exist (confirmed on the UI).

However, I get this error.

```
"Unable to list datastores with name {datastore_name} and version {datastore_version}"
```

### Expected behavior

No error

### Current behavior

Raises an error

### To Reproduce

Steps to reproduce the issue

Configuration I'm using

```
compute:

  provider:
    credentials: ${GRID_PROVIDER_CREDENTIALS}
    region: us-east-1
    vendor: aws

  train:
    disk_size: 200
    instance: t2.2xlarge
    cpus: 7
    gpus: 0
    memory: 32G
    framework: torch

    datastore_name: my_datastore
    datastore_version: 1

```

### Environment

 - OS (e.g., Windows): MacOS
 - Browser (e.g., Chrome, Safari): Chrome
 - CLI version: v0.3.79

### Additional context

I fixed the bug locally, in `client.py`

On line `1829`,

```python
if datastore_version and datastore_version == str(current_version):

# since datastore_version is an integer, this should be
if datastore_version and datastore_version == current_version:
```

And then on line `1841`,

```python
if datastore_version and datastore_version != str(usable_version):

# also, no need to coerce to string
if datastore_version and datastore_version != usable_version:
```
